- pcode: 003
 pname: Fire 7 Kids Edition Tablet
 quantity: 10
 saled: 1
 price: 74.98
- pcode: 002
 pname: EarStudio ES100-24bit Portable High-Resolution Bluetooth
 quantity: 50
 saled: 20
 price: 7.35
- pcode: 004
 pname: Brainwavz 2.55 Balanced Earphone
 quantity: 10
 saled: 1
 price: 8.94 
- pcode: 001
 pname: BagBase Bag bage
 quantity: 10
 saled: 2
 price: 8.94 